name: Build and Merge Firmware

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          version: 'latest'

      - name: Build Firmware
        run: |
          idf.py set-target esp32s3
          idf.py build

      - name: Merge Binaries
        run: |
          esptool.py --chip esp32s3 merge_bin -o merged_firmware.bin \
            0x0 build/bootloader/bootloader.bin \
            0x8000 build/partition_table/partition-table.bin \
            0xe000 build/ota_data_initial.bin \
            0x10000 build/XIAO_Webcam.bin

      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          path: merged_firmware.bin
          name: merged_firmware
