name: CI/CD

on:
  push:
  pull_request:
    branches: ["develop"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target_board: [XIAO-ESP32S3-Sense]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and Merge
        run: |
          mkdir build
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -w /project \
            -u $(id -u) \
            -e HOME=/tmp \
            -e IDF_TARGET=esp32s3 \
            espressif/idf:release-v5.3 \
            bash -c '
              idf.py build &&
              esptool.py --chip esp32s3 merge_bin -o xiao_webcam.bin \
                0x0 build/bootloader/bootloader.bin \
                0x8000 build/partition_table/partition-table.bin \
                0xe000 build/ota_data_initial.bin \
                0x10000 build/XIAO_Webcam.bin
            '
      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir build/${{matrix.target_board}}
          cd build
          awk '{printf "{\"offset\":\"%s\", \"file\":\"%s\"}\n", $1, $2}' offsets.txt | jq -c -s '.' > ${{matrix.target_board}}/offsets.json
          cp bootloader/bootloader.bin partition_table/partition-table.bin ota_data_initial.bin ${{github.event.repository.name}}.bin ${{matrix.target_board}}
          tar -zcf ${{matrix.target_board}}.tar.gz ${{matrix.target_board}}

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/${{matrix.target_board}}.tar.gz
          token: ${{secrets.ACTION_RELEASE_TOKEN}}
          generate_release_notes: true
          make_latest: true


      - name: Upload image to Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: xiao_webcam.bin
          name: xiao_webcam
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true


        
      - name: Push to youseetoo Webtool
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'xiao_webcam.bin'      
          destination_repo: 'youseetoo/youseetoo.github.io'
          destination_folder: 'static/firmware_build'
          user_email: 'bene.d@gmx.de'
          user_name: 'beniroquai'
          commit_message: 'A new firmware binary has been released => https://github.com/youseetoo/uc2-esp32'

